FROM ubuntu:20.04

RUN apt-get update -y && \
    apt-get install -y python3-pip python3-dev

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /GalacticEd/requirements.txt

WORKDIR /GalacticEd

RUN pip3 install -r requirements.txt

COPY . /GalacticEd

EXPOSE 5000

ENTRYPOINT [ "python3" ]

CMD [ "start.py" ]
